name: "JD Docker Image Buildx Dev"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build JD Docker Image Dev
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: evinedeng/jd
          dockerFile: docker/dev/Dockerfile
          platform: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
          tag: unstable
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
